# Generated by Django 5.2.11 on 2026-03-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('d_dob', models.DateField()),
                ('d_email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('d_aadhar', models.CharField(max_length=12)),
                ('specialization', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('p_dob', models.DateField()),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('p_email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('p_aadhar', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=3)),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(null=True)),
                ('time1', models.TimeField(max_length=150)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med', models.CharField(max_length=150)),
                ('dnd', models.CharField(max_length=150)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
